#!/bin/bash

layout="??"

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  layout=`swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name'`;
else
  layout=`xkblayout-state print \"%s\"`;
fi

caps=`cat /sys/class/leds/input*::capslock/brightness | head -n1`;

if [ "$caps" -eq "1" ]; then
  layout=${layout^^}
else
  layout=${layout,,}
fi

layout=" ${layout:1:2}"

# full text
echo $layout

# short text
echo $layout
