#!/bin/bash
#Merry christmas!
#LIGHT=$(( ( RANDOM % 5 )  + 1 ))
LIGHT=0
echo "#85FFFF"

case "$LIGHT" in
   1) echo "#FF0000" 
   ;;
   2) echo "#00FF00" 
   ;;
   3) echo "#0000FF" 
   ;;
   4) echo "#FFFF00" 
   ;;
   5) echo "#FFFF00" 
   ;;
esac
