#!/bin/bash

# Deadbeef
#/usr/bin/deadbeef --nowplaying "%a - %t %e/%l"
#echo ""
#echo ""

# CMus
song_info=$(cmus-remote -Q 2>/dev/null)
artist=$(echo "$song_info" | grep -w '^tag artist' | cut -d ' ' -f3-)
song=$(echo "$song_info" | grep -w '^tag title' | cut -d ' ' -f3-)
if [[ ! -z "$artist" && ! -z "$song" ]]; then
  echo "$artist - $song"
  echo "$artist - $song"
else
  file=$(basename "$(echo "$song_info" | grep -w '^file' | cut -d ' ' -f2-)")
  echo $file
  echo $file
fi
