#!/bin/bash

# Deadbeef
#/usr/bin/deadbeef --nowplaying "%a - %t %e/%l"
#echo ""
#echo ""

# CMus
artist=$(cmus-remote -Q | grep -w '^tag artist' | cut -d ' ' -f3-)
song=$(cmus-remote -Q | grep -w '^tag title' | cut -d ' ' -f3-)
if [[ ! -z "$artist" && ! -z "$song" ]]; then
  echo "$artist - $song"
  echo "$artist - $song"
else
  file=$(basename "$(cmus-remote -Q | grep file | cut -d ' ' -f2-)")
  echo $file
  echo $file
fi
