#!/bin/bash
# SPDX-License-Identifier: Unlicense

set -e

format() {
  local volume=$1
  local muted=$2
  if [ "yes" = "$muted" ]; then
    echo " "
  else
    echo " ${volume}%"
  fi
}

default_sink=$(pactl get-default-sink)

case $BLOCK_BUTTON in
  3) pactl set-sink-mute ${default_sink} toggle ;; # right click, mute/unmute
  4)
    pactl set-sink-mute ${default_sink} 0;
    pactl set-sink-volume ${default_sink} +5% ;; # scroll up, increase
  5)
    pactl set-sink-mute ${default_sink} 0;
    pactl set-sink-volume ${default_sink} -5% ;; # scroll down, decrease
esac

volume=$(pactl get-sink-volume ${default_sink} | sed -nE 's/^Volume:.* ([0-9]{1,3})%.*/\1/p')
muted=$(pactl get-sink-mute ${default_sink} | sed -nE 's/Mute:\s*(yes|no)/\1/p')

# i3blocks requires two representations: short and long.
# In this case short and long representations are identical.
format ${volume} ${muted}
format ${volume} ${muted}
