#!/bin/zsh
scrot \
-s '%Y-%m-%d_%H:%M:%S_$wx$h.png' \
-e 'mv $f /home/oxore/Pictures/shots/; cp /home/oxore/Pictures/shots/$f ~/Pictures/shots/1-last.png'
chromium /home/oxore/Pictures/shots/1-last.png
