#!/bin/sh

BUILDPKGS=/tmp/build-pkgs
ARCHTREE=archtree
PKGDIR=pkg

update_with_valgrind()
{
  if [ -d $1 ]; then
    cd ./$1/trunk
    sed -i 's/valgrind=false/valgrind=true/' PKGBUILD
    makepkg
    cp *.pkg.tar.xz $BUILDPKGS/$PKGDIR/
    cd ../..
  else
    echo "Error: no such package \"$1\""
  fi
}

[ ! -d $BUILDPKGS ] && mkdir -p $BUILDPKGS
[ ! -d $BUILDPKGS/$PKGDIR ] && mkdir -p $BUILDPKGS/$PKGDIR
cd $BUILDPKGS
[ ! -d $ARCHTREE ] && git clone --depth=1 git://git.archlinux.org/svntogit/packages.git $ARCHTREE
cd $ARCHTREE
update_with_valgrind libdrm
update_with_valgrind mesa
cd $BUILDPKGS
rm -rf $ARCHTREE
